### ISSUE TITLE
Web access doesn't work when using dorowu/ubuntu-desktop-lxde-vnc:bionic as base image for neurodocker

### ISSUE THREAD

**Issue by civier** [NeuroDesk/masterVNM#1]
I used neurodocker to build a container with a lot of software and dorowu/ubuntu-desktop-lxde-vnc:bionic base image (I manually removed the ENTRYPOINT line in the resulting Dockerfile, so as to maintain the original ENTRYPOINT of dorowu/ubuntu-desktop-lxde-vnc:bionic):
> sudo docker run --rm kaczmarj/neurodocker:0.6.0 generate docker \
> --base dorowu/ubuntu-desktop-lxde-vnc:bionic \
> --pkg-manager apt --afni version=latest --ants version=2.3.1 --freesurfer version=6.0.0-min \
> --fsl version=5.0.11 --matlabmcr version=2018a --mrtrix3 version=3.0_RC3 > Dockerfile
 
The container runs ok, but when I try to connect to it with the browser, it doesn't work, and the following error is printed by the container:
> 2020-06-22 02:58:44,665 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:44] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.165175
> >>> sending remote command: "cmd=fb" via X11VNC_REMOTE X property.
> 2020-06-22 02:58:45,826 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:45,834 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:45] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.159158
> >>> sending remote command: "cmd=fb" via X11VNC_REMOTE X property.
> 2020-06-22 02:58:46,992 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:47,001 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:47] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.158364
> 2020-06-22 02:58:47,303 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:47,312 ERROR Exception on /api/health [GET] (app.py:1761)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 41, in apihealth
>     if state.health:
>   File "/usr/local/lib/web/backend/vnc/state.py", line 129, in health
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:47] "GET /api/health HTTP/1.1" 500 412 0.127645
> >>> sending remote command: "cmd=fb" via X11VNC_REMOTE X property.
> 2020-06-22 02:58:48,156 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:48,164 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:48] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.154937
> >>> sending remote command: "cmd=fb" via X11VNC_REMOTE X property.
> 2020-06-22 02:58:49,315 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:49,323 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:49] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.152794
> >>> sending remote command: "cmd=fb" via X11VNC_REMOTE X property.
> 2020-06-22 02:58:50,482 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:58:50,490 ERROR Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2 (response.py:36)
> Traceback (most recent call last):
>   File "/usr/local/lib/web/backend/vnc/response.py", line 28, in func
>     return f(*args, **kwargs)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 32, in apistate
>     mystate = state.to_dict()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 45, in to_dict
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:58:50] "GET /api/state?video=false&id=-1&w=921&h=418 HTTP/1.0" 200 270 0.160652
> 2020-06-22 02:59:17,691 CRIT Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 354, in continue_request
>     params, method = self.loads(data)
>   File "/usr/local/lib/python2.7/dist-packages/supervisor/xmlrpc.py", line 585, in loads
>     for action, elem in iterparse(StringIO(data)):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1203, in iterparse
>     parser = XMLParser(target=TreeBuilder())
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1482, in __init__
>     "No module named expat; use SimpleXMLTreeBuilder instead"
> ImportError: No module named expat; use SimpleXMLTreeBuilder instead
> 
> 2020-06-22 02:59:17,703 ERROR Exception on /api/health [GET] (app.py:1761)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/web/backend/vnc/app.py", line 41, in apihealth
>     if state.health:
>   File "/usr/local/lib/web/backend/vnc/state.py", line 129, in health
>     self._update_health()
>   File "/usr/local/lib/web/backend/vnc/state.py", line 33, in _update_health
>     'status'
>   File "/usr/local/lib/python2.7/dist-packages/gevent/subprocess.py", line 332, in check_output
>     raise CalledProcessError(retcode, process.args, output=output)
> CalledProcessError: Command '['supervisorctl', '-c', '/etc/supervisor/supervisord.conf', 'status']' returned non-zero exit status 2
> 127.0.0.1 - - [2020-06-22 02:59:17] "GET /api/health HTTP/1.1" 500 412 0.127141

@stebo85, any ideas what is the problem? Did you get something similar when you built the vnm container? (just to clarify, I'm working on a NECTAR VM, and dorowu/ubuntu-desktop-lxde-vnc:bionic runs fine as-is)

**Comment by civier** [comment]
Is it possible that it is a python2/python3 issue? as I see python 3 is first in path.

**Comment by stebo85** [comment]
Dear @civier,

It looks like a dependency problem and that's just one reason why I am convinced that it is not a good idea to build a big super container with everything installed in the main container. In my opinion, the neuro imaging software has to be installed in sub-containers to avoid dependency problems and that's exactly what we are all trying to do! To achieve what you want, you only need to add the existing software containers to the menu system in the current master branch image and it will already work nicely and scale and it will also be maintainable in the long run :)

Best
steffen
